export { BackgroundImage } from "./BackgroundImage";
export { Footer } from "./Footer";
export { FormField } from "./FormField";
export { Loadable } from "./Loadable";
export { Loading } from "./Loading";
// export { LoginForm } from "./Auth/LoginForm";
// export { SignUpForm } from "./Auth/SignUpForm";
// export { OTPCodeForm } from "./Auth/OTPCodeForm";
// export { ForgotPasswordForm } from "./Auth/ForgotPasswordForm";
// export { ResetPasswordForm } from "./Auth/ResetPasswordForm";

export { Navbar } from "./NavBar";
export { Sidebar } from "./Sidebar/Sidebar";
export { ShowApp } from "./ShowApp";
export { Template } from "./Auth/Template";
export { Tab } from "./UI/Tab";
export { Title } from "./UI/Title";
export { DeleteAccount } from "./Settings/DeleteAccount";
export { EditProfile } from "./Settings/EditProfile";
export { ChangePassword } from "./Settings/ChangePassword";
export { PersonalDetails } from "./Settings/PersonalDetails";
export { UserInfo } from "./Settings/UserInfo";
