export { Tab } from "./UI/Tab";
export { Footer } from "./Footer";
export { Navbar } from "./NavBar";
export { Image } from "./UI/Image";
export { Title } from "./UI/Title";
export { ShowApp } from "./ShowApp";
export { Loading } from "./Loading";
export { TopPlay } from "./TopPlay";
export { Modal } from "./UI/Modals";
export { Button } from "./UI/Button";
export { Language } from "./Language";
export { FormField } from "./FormField";
export { Searchbar } from "./SearchBar";
export * from "./UI/Modals/ModalContent";
export * from "./Common/GameDetailCommon";
export { HomeFooter } from "./HomeFooter";
export { FormTemplate } from "./Auth/FormTemplate";
export { Sidebar } from "./Sidebar/Sidebar";
export { Profile } from "./Profile/Profile";
export { ReadMore } from "./Common/ReadMore";
export { UserInfo } from "./Profile/UserInfo";
export { Notification } from "./Notification";
export { MediaCard } from "./Cards/MediaCard";
export { SocialAuth } from "./Auth/SocialAuth";
// export { LoginForm } from "./Auth/LoginForm";
export { TopPlayCard } from "./Cards/TopPlayCard";
export { CartSwitcher } from "./Cart/CartSwitcher";
export { EditProfile } from "./Profile/EditProfile";
// export { OTPCodeForm } from "./Auth/OTPCodeForm";
export { GameDetail } from "./GameDetail/GameDetail";
export { MediaSection } from "./Sections/MediaSection";
export { DeleteAccount } from "./Profile/DeleteAccount";
export { ChangePassword } from "./Profile/ChangePassword";
export { TopPlaySection } from "./Sections/TopPlaySection";
export { ProfileDropdown } from "./Profile/ProfileDropDown";
export { PersonalDetails } from "./Profile/PersonalDetails";
export { ErrorFormMessage } from "./Common/ErrorFormMessage";
export { DeleteProfileModal } from "./UI/Modals/DeleteProfileModal";
export { SessionExpiredModal } from "./UI/Modals/SessionExpiredModal";
export { ChangeProfilePhotoModal } from "./UI/Modals/ChangeProfilePhotoModal";
export { TabTitle } from "./Common/TabTittle";
